spring.datasource.url=jdbc:h2:mem:gymcrm_local;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.hikari.maximum-pool-size=5

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.metrics.tags.environment=local

logging.level.com.daniel.taskspringcore=DEBUG
logging.level.org.hibernate.SQL=DEBUG
