spring.application.name=taskspringcore

spring.datasource.url=jdbc:postgresql://localhost:5432/gymcrm
spring.datasource.username=gym
spring.datasource.password=gym

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
