spring.application.name=taskspringcore
spring.profiles.default=local

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never
management.endpoint.health.show-components=always
management.endpoint.health.status.http-mapping.down=503
management.endpoint.health.status.http-mapping.out-of-service=200
management.info.env.enabled=true

management.metrics.tags.application=${spring.application.name}
management.metrics.tags.environment=unknown

info.app.name=Gym CRM
info.app.description=Gym CRM REST API with trainee, trainer and training management
