spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:gymcrm_dev}
spring.datasource.username=${DB_USERNAME:gym}
spring.datasource.password=${DB_PASSWORD:gym}
spring.datasource.hikari.maximum-pool-size=10

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

management.endpoints.web.exposure.include=health,info,metrics,prometheus,env,loggers,beans,mappings
management.endpoint.health.show-details=always
management.metrics.tags.environment=dev

logging.level.com.daniel.taskspringcore=DEBUG
